ZCS- 5471
Zimbra/zm-taglib pull request #29
Opened 2019-04-09 03:41 UTC by rupalid

Upgrading HttpClient library.

Verified "ant publish-local" works.

The functionality will be verified when all the changes with Http client upgrade are in place.

2019-04-09 03:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zimbra/zm-taglib?pullRequest=29) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Zimbra/zm-taglib?pullRequest=29) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: root<br/>:x: rupalid<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zimbra/zm-taglib?pullRequest=29) it.</sub>

2019-04-09 05:21 UTC, chinmay15 commented on src/java/com/zimbra/cs/taglib/tag/briefcase/SaveBriefcaseTag.java
> +                        	Map<String,byte[]> attachment = new HashMap<String,byte[]>();
indentation

2019-04-09 05:21 UTC, chinmay15 approved these changes

2019-04-09 07:36 UTC, jrjena136 approved these changes

2019-04-09 15:22 UTC, desouzas requested changes

2019-04-10 03:38 UTC, rupalid commented on src/java/com/zimbra/cs/taglib/tag/GetInfoJSONTag.java
> +                options.setUserAgent(originalUserAgent, SoapProtocol.Soap12.getVersion());
Fixed

2019-04-10 03:55 UTC, desouzas approved these changes

2019-04-11 23:54 UTC, merged